import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa-reseller.blubirch.com:3805/');
  await page.getByRole('textbox', { name: 'Enter email ID/phone number/' }).click();
          await page.getByRole('textbox', { name: 'Enter email ID/phone number/' }).fill('dava_admin');
          await page.getByRole('textbox', { name: 'Enter Password' }).click();
          await page.getByRole('textbox', { name: 'Enter Password' }).fill('blubirch@123');
          await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('RIMS').click();
  await page.getByRole('link', { name: 'PRD' }).click();
  await page.getByRole('tab', { name: 'Incomplete PRDs' }).click();
  await page.getByRole('tab', { name: 'Open PRDs' }).click();
  await page.getByRole('tab', { name: 'Approval', exact: true }).click();
  await page.getByRole('tab', { name: 'Pending For Approval' }).click();
  await page.getByText('Disposition', { exact: true }).click();
  await page.getByRole('link', { name: 'Brand Call Log Quantity 1580' }).click();
  await page.getByRole('tab', { name: 'Pending BCL Tickets' }).click();
  await page.getByRole('tab', { name: 'Pending Inspection' }).click();
  await page.getByRole('tab', { name: 'Pending Decision' }).click();
  await page.getByRole('tab', { name: 'Pending Disposition' }).click();
  await page.getByRole('tablist').locator('i').nth(1).click();
  await page.getByRole('tab', { name: 'Pending For Approval' }).click();
  await page.locator('.active-list-item1a').click();
  await page.getByRole('link', { name: 'Markdown Quantity 438 Average' }).click();
  await page.getByRole('tab', { name: 'Dispatch' }).click();
  await page.getByRole('tab', { name: 'Pending For Approval' }).click();
  await page.locator('.active-list-item1a').click();
  await page.getByRole('link', { name: 'Insurance Quantity 773' }).click();
  await page.getByRole('tab', { name: 'Pending Claim Ticket' }).click();
  await page.getByRole('tab', { name: 'Pending Inspection' }).click();
  await page.getByRole('tab', { name: 'Pending Decision' }).click();
  await page.getByRole('tab', { name: 'Pending Disposition' }).click();
  await page.getByRole('tablist').locator('i').nth(1).click();
  await page.getByRole('tab', { name: 'Pending For Approval' }).click();
  await page.locator('.active-list-item1a').click();
  await page.getByRole('link', { name: 'Liquidation Quantity 2135' }).click();
  await page.getByRole('tab', { name: 'Sales Method' }).click();
  await page.getByRole('tab', { name: 'Create Lots' }).click();
  await page.getByText('Contracted').click();
  await page.getByRole('tab', { name: 'Create Lots (Con)' }).click();
  await page.getByText('Competitive').click();
  await page.getByRole('tab', { name: 'Publish' }).click();
  await page.getByText('B2B').click();
  await page.getByRole('tab', { name: 'Publish' }).click();
  await page.locator('div').filter({ hasText: /^B2C$/ }).first().click();
  await page.getByRole('tab', { name: 'In Progress' }).click();
  await page.getByText('B2B').click();
  await page.getByRole('tab', { name: 'In Progress' }).click();
  await page.getByText('B2C').click();
  await page.getByRole('tab', { name: 'Pending Dec' }).click();
  await page.getByRole('tab', { name: 'Lot Approval' }).click();
  await page.getByRole('tablist').locator('i').nth(4).click();
  await page.getByRole('tab', { name: 'Pending Pmt' }).click();
  await page.getByRole('tab', { name: 'Lot Handover' }).click();
  await page.getByRole('tab', { name: 'Dispatch' }).click();
  await page.getByRole('tab', { name: 'Pending For Approval' }).click();
});